import { createAudioState, playSfx, toggleAudio } from "./gameAudio.js";
import { drawMinimap, drawScene } from "./gameCanvas.js";
import { createBlossomPlan, createEmployees, createPool, HORIZON, INITIAL_CASH, MEDIA, OFFSETS, PATTERN, START, TEMPLATES, WEATHER } from "./gameData.js";
import { buildConflicts, renderUi } from "./gameUi.js";
import { PERIOD_MS, addDays, avg, choice, clamp, lerp, md, money, randInt, stamp, uniq } from "./gameUtils.js";

export function createGame({ canvas, minimapCanvas, statsRoot }) {
  const ctx = canvas?.getContext("2d");
  const mini = minimapCanvas?.getContext("2d");
  if (!ctx || !mini || !statsRoot) return;
  const employees = createEmployees();
  const refs = {
    root: statsRoot, run: statsRoot.querySelector("[data-action='toggle-run']"), audio: statsRoot.querySelector("[data-action='open-audio']"), title: statsRoot.querySelector("[data-scene-title]"),
    roster: statsRoot.querySelector("[data-roster]"), detail: statsRoot.querySelector("[data-employee-detail]"), talent: statsRoot.querySelector("[data-talent]"), event: statsRoot.querySelector("[data-event]"), pattern: statsRoot.querySelector("[data-pattern]"),
    conflicts: statsRoot.querySelector("[data-conflicts]"), board: statsRoot.querySelector("[data-board]"), dash: statsRoot.querySelector("[data-dashboards]"), tutorial: statsRoot.querySelector("[data-tutorial]"), log: statsRoot.querySelector("[data-log]"),
    alert: statsRoot.querySelector("[data-overlay='alerts']"), clock: statsRoot.querySelector("[data-overlay='clock']"), legend: statsRoot.querySelector("[data-overlay='legend']")
  };
  const state = {
    canvas, minimapCanvas, ctx, mini, refs, employees, map: new Map(employees.map((employee) => [employee.id, employee])), pool: createPool(), slots: {}, byPeriod: {}, horizon: -1, current: 0, running: false, runAcc: 0, frame: 0, last: performance.now(),
    filter: "all", selected: employees[0]?.id || null, drag: null, history: [], future: [], logs: [], dirty: true, focus: "core", pan: { x: 0, y: 0 }, target: { x: -60, y: 20 }, weather: {}, nextEvt: randInt(4, 6),
    blossom: createBlossomPlan(), mods: { market: 1, reg: 0.18, labor: 0.12, recruit: 0.08, bloomBias: 0 }, progs: { training: 0, handover: 0 }, audio: createAudioState(),
    stats: { cash: INITIAL_CASH, uptime: 91, trir: 0.62, harmony: 76, community: 69, fatigue: avg(employees.map((employee) => employee.fatigue)), succession: 0 },
    fin: { revenue: 0, salary: 0, overtime: 0, training: 0, recruit: 0, welfare: 0, event: 0, last: { net: 0, revenue: 0, salary: 0, overtime: 0, training: 0, welfare: 0, event: 0 } },
    alerts: [],
  };
  note(state, "Init", "Workforce model loaded.");
  note(state, "Forecast", `Blossom forecast: ${md(addDays(START, state.blossom.forecast))}.`);
  note(state, "Economy", "Operating cash seeded at $200,000,000.");
  syncDerived(state); ensure(state); bind(state); refresh(state); requestAnimationFrame((time) => loop(state, time));
}

function bind(state) {
  state.refs.root.addEventListener("click", (event) => {
    const action = event.target.closest("[data-action]")?.dataset.action, filter = event.target.closest("[data-filter]")?.dataset.filter, select = event.target.closest("[data-select-employee]")?.dataset.selectEmployee, remove = event.target.closest("[data-remove-assignment]"), eventAction = event.target.closest("[data-event-action]");
    if (action) return handleAction(state, action);
    if (filter) { state.filter = filter; state.refs.root.querySelectorAll("[data-filter]").forEach((node) => node.classList.toggle("is-active", node.dataset.filter === filter)); return dirty(state); }
    if (select) { state.selected = select; return dirty(state); }
    if (remove) return unassign(state, remove.dataset.slotId, remove.dataset.removeAssignment);
    if (eventAction) return handleEventAction(state, eventAction.dataset.eventAction, eventAction.dataset.value || null);
  });
  state.refs.roster.addEventListener("dragstart", (event) => { const id = event.target.closest("[data-employee-id]")?.dataset.employeeId; if (!id) return; state.drag = id; event.dataTransfer.effectAllowed = "copy"; event.dataTransfer.setData("text/plain", id); });
  state.refs.roster.addEventListener("dragend", () => { state.drag = null; clearDrop(state); });
  state.refs.board.addEventListener("dragover", (event) => { const slot = event.target.closest("[data-slot-id]"); if (!slot) return; event.preventDefault(); clearDrop(state); slot.classList.add("is-drop-target"); });
  state.refs.board.addEventListener("dragleave", (event) => event.target.closest("[data-slot-id]")?.classList.remove("is-drop-target"));
  state.refs.board.addEventListener("drop", (event) => { const slot = event.target.closest("[data-slot-id]"), id = event.dataTransfer.getData("text/plain") || state.drag; if (!slot || !id) return; event.preventDefault(); clearDrop(state); assign(state, slot.dataset.slotId, id); });
}

function handleAction(state, action) {
  if (action === "toggle-run") state.running = !state.running;
  if (action === "advance-12h") advance(state, 1);
  if (action === "advance-day") advance(state, 2);
  if (action === "focus-core") { state.focus = "core"; note(state, "Scene", "Camera moved to process core."); }
  if (action === "focus-blossom") { state.focus = "blossom"; note(state, "Scene", "Camera moved to blossom walkway."); }
  if (action === "undo") undo(state);
  if (action === "redo") redo(state);
  if (action === "open-audio") toggleAudio(state, (tag, text) => note(state, tag, text));
  if (action === "auto-mentor") mentor(state);
  if (action === "run-training") training(state);
  if (action === "run-handover") handover(state);
  if (action === "emergency-recruit") recruit(state);
  dirty(state);
}

function handleEventAction(state, action, value) {
  if (action === "date-minus") state.blossom.open = clamp(state.blossom.open - 1, 4, 14);
  if (action === "date-plus") state.blossom.open = clamp(state.blossom.open + 1, 4, 14);
  if (action === "duration-toggle") state.blossom.duration = state.blossom.duration === 6 ? 7 : 6;
  if (action === "family-toggle") state.blossom.perks = !state.blossom.perks;
  if (action === "media") state.blossom.media = value;
  rebuild(state);
  note(state, "Event", `Blossom setup updated: ${md(addDays(START, state.blossom.open))}, ${state.blossom.duration} days, ${MEDIA[state.blossom.media].label}.`);
  dirty(state);
}

function advance(state, count) { for (let step = 0; step < count; step += 1) { ensure(state); simulate(state, resolve(state, state.current)); state.current += 1; prune(state); ensure(state); if (state.current >= state.nextEvt) { randomEvent(state); state.nextEvt = state.current + randInt(3, 5); } } syncDerived(state); dirty(state); }
function refresh(state) { const view = buildView(state), helpers = uiHelpers(state); renderUi(state, view, buildConflicts(state, view, (employee, info, slot) => available(state, employee, info, slot)), helpers); const zoneHeat = helpers.zoneHeat(); drawScene(state, helpers.periodInfo(state.current), helpers.weatherKey(helpers.dayNow()), zoneHeat, helpers.bloom()); drawMinimap(state, zoneHeat); state.dirty = false; }
function loop(state, time) { const delta = Math.min(0.05, (time - state.last) / 1000); state.last = time; state.frame += delta; state.target = state.focus === "blossom" ? { x: 130, y: -30 } : { x: -60, y: 20 }; state.pan.x = lerp(state.pan.x, state.target.x, delta * 2.2); state.pan.y = lerp(state.pan.y, state.target.y, delta * 2.2); if (state.running) { state.runAcc += delta; if (state.runAcc >= 1.25) { state.runAcc -= 1.25; advance(state, 1); } } const helpers = uiHelpers(state); const zoneHeat = helpers.zoneHeat(); drawScene(state, helpers.periodInfo(state.current), helpers.weatherKey(helpers.dayNow()), zoneHeat, helpers.bloom()); drawMinimap(state, zoneHeat); if (state.dirty) refresh(state); requestAnimationFrame((next) => loop(state, next)); }
function uiHelpers(state) { return { dayNow: () => Math.floor(state.current / 2), eventDay: (day) => day >= state.blossom.open && day < state.blossom.open + state.blossom.duration, weatherKey: (day) => weatherKey(state, day), crewShift: (crew, day) => PATTERN[(day + OFFSETS[crew]) % PATTERN.length], currentSlots: () => resolve(state, state.current).slots, filteredEmployees: () => state.employees.filter((employee) => employee.active && (state.filter === "all" || employee.workType === state.filter)).sort((a, b) => (a.workType === b.workType ? b.fatigue - a.fatigue : a.workType.localeCompare(b.workType))), periodInfo, zoneHeat: () => zoneHeat(state), bloom: () => clamp(1 - Math.abs(Math.floor(state.current / 2) - state.blossom.forecast) / 10, 0.18, 0.95) }; }

function buildView(state) { return Array.from({ length: HORIZON }, (_, index) => resolve(state, state.current + index)); }
function periodInfo(index) { const date = new Date(START.getTime() + index * PERIOD_MS); return { index, dayIndex: Math.floor(index / 2), date, shift: index % 2 === 0 ? "day" : "night", label: `${md(date)} ${index % 2 === 0 ? "day" : "night"}` }; }
function ensure(state) { for (let periodIndex = state.horizon + 1; periodIndex < state.current + HORIZON; periodIndex += 1) buildPeriod(state, periodIndex); state.horizon = Math.max(state.horizon, state.current + HORIZON - 1); }
function buildPeriod(state, periodIndex) { const info = periodInfo(periodIndex); state.byPeriod[periodIndex] = TEMPLATES.filter((template) => template.shifts.includes(info.shift) && (!template.eventOnly || eventDay(state, info.dayIndex))).map((template) => (state.slots[`${periodIndex}:${template.id}`] = { ...template, id: `${periodIndex}:${template.id}`, periodIndex, manual: null }).id); }
function rebuild(state) { const manual = new Map(); Object.values(state.slots).forEach((slot) => slot.periodIndex >= state.current && slot.manual !== null && manual.set(slot.id, [...slot.manual])); Object.keys(state.slots).forEach((id) => state.slots[id].periodIndex >= state.current && delete state.slots[id]); Object.keys(state.byPeriod).forEach((key) => Number(key) >= state.current && delete state.byPeriod[key]); state.horizon = state.current - 1; ensure(state); manual.forEach((value, id) => state.slots[id] && (state.slots[id].manual = value)); }
function prune(state) { Object.keys(state.byPeriod).forEach((key) => { if (Number(key) < state.current - 2) { state.byPeriod[key].forEach((id) => delete state.slots[id]); delete state.byPeriod[key]; } }); }

function resolve(state, periodIndex) { const info = periodInfo(periodIndex), defs = (state.byPeriod[periodIndex] || []).map((id) => state.slots[id]).filter(Boolean), locked = new Set(), used = new Set(), slots = []; defs.filter((slot) => slot.manual !== null).forEach((slot) => { const employeeIds = slot.manual.filter((id) => state.map.get(id)?.active); employeeIds.forEach((id) => locked.add(id)); slots.push(makeView(state, slot, info, employeeIds, true)); }); defs.filter((slot) => slot.manual === null).sort((a, b) => b.w - a.w).forEach((slot) => { const employeeIds = []; [true, false].forEach((strict) => candidates(state, slot, info, strict).forEach((employee) => { if (employeeIds.length >= slot.need || locked.has(employee.id) || used.has(employee.id) || employeeIds.includes(employee.id)) return; employeeIds.push(employee.id); used.add(employee.id); })); slots.push(makeView(state, slot, info, employeeIds, false)); }); return { info, slots: slots.sort((a, b) => b.w - a.w) }; }
function candidates(state, slot, info, strict) { return state.employees.filter((employee) => employee.active && slot.types.includes(employee.workType) && (!strict ? !(employee.workType === "day" && info.shift === "night") : available(state, employee, info, slot))).sort((a, b) => fit(state, b, slot, info, strict) - fit(state, a, slot, info, strict)); }
function available(state, employee, info, slot) { if (!slot.types.includes(employee.workType)) return false; if (employee.workType === "shift") return PATTERN[(info.dayIndex + OFFSETS[employee.crew]) % PATTERN.length] === info.shift; const weekday = addDays(START, info.dayIndex).getDay(); return info.shift === "day" && (weekday >= 1 && weekday <= 5 || slot.zone === "blossom" || slot.zone === "hq"); }
function fit(state, employee, slot, info, strict) { return avg(slot.keys.map((key) => employee.skills[key] || 18)) + employee.successionReadiness * 0.2 + employee.morale * 0.18 + employee.safety * 0.22 + (employee.primary === slot.zone ? 15 : employee.secondary.includes(slot.zone) ? 8 : 0) + (employee.mentorId ? 6 : 0) + (available(state, employee, info, slot) ? 16 : strict ? -80 : -18) - employee.fatigue * 0.5; }
function makeView(state, slot, info, employeeIds, manual) { const employees = employeeIds.map((id) => state.map.get(id)).filter(Boolean), coverage = clamp(employeeIds.length / slot.need, 0, 1), skill = employees.length ? avg(employees.map((employee) => avg(slot.keys.map((key) => employee.skills[key] || 18)))) / 100 : 0, safety = employees.length ? avg(employees.map((employee) => employee.safety)) / 100 : 0, fatigue = employees.length ? avg(employees.map((employee) => employee.fatigue)) / 100 : 0, senior = employees.some((employee) => employee.experienceYears >= 15); return { ...slot, employeeIds, people: employees, cov: coverage, q: clamp(coverage * 0.5 + skill * 0.28 + safety * 0.18 + (senior ? 0.06 : 0) - fatigue * 0.16, 0, 1), senior, off: employees.some((employee) => !available(state, employee, info, slot)), manual }; }

function simulate(state, resolved) {
  const prod = resolved.slots.filter((slot) => ["control", "cracker", "olefins", "aromatics", "utilities", "tankFarm"].includes(slot.zone)), support = resolved.slots.filter((slot) => !prod.includes(slot)), eventSlot = resolved.slots.find((slot) => slot.zone === "blossom"), duplicateCount = countDuplicates(resolved.slots), mismatchCount = countMismatches(resolved.slots, resolved.info), offCount = resolved.slots.reduce((sum, slot) => sum + (slot.off ? 1 : 0), 0), avgFatigue = avg(uniq(resolved.slots.flatMap((slot) => slot.employeeIds)).map((id) => state.map.get(id)?.fatigue || 0)), weather = WEATHER[weatherKey(state, resolved.info.dayIndex)], eventActive = eventDay(state, resolved.info.dayIndex) && resolved.info.shift === "day", eventScore = eventSlot ? clamp(eventSlot.q * 0.75 + avg(support.map((slot) => slot.q)) * 0.25, 0, 1) : 0, safetyDesk = resolved.slots.find((slot) => slot.id.includes("safetyDesk")), safetyBase = clamp((safetyDesk?.q || 0.68) * 0.45 + (1 - avgFatigue / 100) * 0.2 + (1 - state.mods.reg * 0.6) * 0.15 + (1 - mismatchCount * 0.05) * 0.2, 0, 1), incident = Math.random() < clamp(0.04 + (1 - safetyBase) * 0.26 + mismatchCount * 0.05 + duplicateCount * 0.05 + offCount * 0.03 + (eventActive ? (1 - eventScore) * 0.12 : 0), 0.02, 0.72), uptime = clamp(weighted(prod) * 0.78 + avg(support.map((slot) => slot.q)) * 0.1 + weather.prod * 0.12 - duplicateCount * 0.02 - mismatchCount * 0.03, 0.38, 1), revenue = 2_850_000 * state.mods.market * uptime * weather.prod, salary = state.employees.filter((employee) => employee.active).reduce((sum, employee) => sum + pay(employee), 0), overtime = offCount * 42_000 + duplicateCount * 18_000, welfare = eventActive && state.blossom.perks ? 78_000 : 0, eventCost = eventActive ? 220_000 * MEDIA[state.blossom.media].crowd : 0, trainingCost = (state.progs.training ? 55_000 : 0) + (state.progs.handover ? 32_000 : 0), total = salary + overtime + welfare + eventCost + trainingCost;
  state.fin.revenue += revenue; state.fin.salary += salary; state.fin.overtime += overtime; state.fin.training += trainingCost; state.fin.welfare += welfare; state.fin.event += eventCost; state.stats.cash += revenue - total; state.fin.last = { net: revenue - total, revenue, salary, overtime, training: trainingCost, welfare, event: eventCost };
  state.stats.uptime = lerp(state.stats.uptime, uptime * 100, 0.34); state.stats.fatigue = lerp(state.stats.fatigue, avgFatigue, 0.28); state.stats.harmony = clamp(lerp(state.stats.harmony, 76 - offCount * 3.2 - state.mods.labor * 22 + (eventActive && state.blossom.perks ? 4 : 0), 0.2), 18, 100); state.stats.community = clamp(lerp(state.stats.community, 68 + (eventActive ? eventScore * 22 : 0) + MEDIA[state.blossom.media].rep * 10 - (incident ? 10 : 0), 0.24), 12, 100); state.stats.trir = clamp(lerp(state.stats.trir, Math.max(0.16, state.stats.trir + (incident ? 0.18 : -0.02) + (1 - uptime) * 0.08), 0.34), 0.14, 2.5);
  const assigned = new Map(); resolved.slots.forEach((slot) => slot.employeeIds.forEach((id) => assigned.set(id, slot))); state.employees.forEach((employee) => updateEmployee(state, employee, resolved.info, assigned.get(employee.id), incident, eventActive)); scoreEvent(state, resolved.info.dayIndex, eventActive ? eventScore : null); if (resolved.info.shift === "day" && Math.random() < 0.015 + state.mods.labor * 0.02 + (resolved.info.dayIndex > 8 ? 0.012 : 0)) retire(state); decay(state); note(state, incident ? "Safety" : eventActive && eventScore >= 0.75 ? "Community" : "Ops", incident ? `Incident risk materialized during ${resolved.info.label}.` : eventActive && eventScore >= 0.75 ? `Blossom day landed at ${Math.round(eventScore * 100)} quality.` : `${resolved.info.label}: uptime ${Math.round(uptime * 100)}% / net ${money(state.fin.last.net)}.`); }
function updateEmployee(state, employee, info, slot, incident, eventActive) { if (!employee.active) return; const mentor = employee.mentorId ? state.map.get(employee.mentorId) : null; if (slot) { const offPattern = !available(state, employee, info, slot); employee.fatigue = clamp(employee.fatigue + 7 + (offPattern ? 5 : 0) + employee.commutePressure * 0.03, 0, 100); employee.morale = clamp(employee.morale + (eventActive && slot.zone === "blossom" ? 2.8 : 0.5) - (offPattern ? 3.6 : 0) - (employee.fatigue > 70 ? 2.2 : 0), 0, 100); employee.recent = [...employee.recent, info.index].slice(-16); if (state.progs.training && ["training", "hq", "blossom"].includes(slot.zone)) { employee.successionReadiness = clamp(employee.successionReadiness + 1.8, 0, 100); employee.safety = clamp(employee.safety + 0.8, 0, 100); } if (state.progs.handover && (mentor || employee.menteeIds.length)) employee.successionReadiness = clamp(employee.successionReadiness + 1.2, 0, 100); } else { employee.fatigue = clamp(employee.fatigue - 6.2, 0, 100); employee.morale = clamp(employee.morale + 0.9, 0, 100); } if (incident && slot) { employee.morale = clamp(employee.morale - 2.8, 0, 100); employee.fatigue = clamp(employee.fatigue + 1.6, 0, 100); } }
function assign(state, slotId, employeeId) { const slot = state.slots[slotId], resolved = resolve(state, slot.periodIndex), current = slot.manual !== null ? [...slot.manual] : [...(resolved.slots.find((entry) => entry.id === slotId)?.employeeIds || [])]; if (!slot || !state.map.get(employeeId)?.active || current.includes(employeeId)) return; const before = slot.manual === null ? null : [...slot.manual], after = [...current, employeeId]; slot.manual = after; state.history.push({ slotId, before, after }); state.future = []; note(state, "Schedule", `Assigned ${state.map.get(employeeId).name} to ${slot.label}.`); playSfx(state, "assign"); dirty(state); }
function unassign(state, slotId, employeeId) { const slot = state.slots[slotId], resolved = resolve(state, slot.periodIndex), current = slot.manual !== null ? [...slot.manual] : [...(resolved.slots.find((entry) => entry.id === slotId)?.employeeIds || [])]; if (!slot || !current.includes(employeeId)) return; const before = slot.manual === null ? null : [...slot.manual], after = current.filter((id) => id !== employeeId); slot.manual = after; state.history.push({ slotId, before, after }); state.future = []; note(state, "Schedule", `Removed ${state.map.get(employeeId)?.name || "employee"} from ${slot.label}.`); playSfx(state, "soft"); dirty(state); }
function undo(state) { const entry = state.history.pop(); if (!entry || !state.slots[entry.slotId]) return; state.slots[entry.slotId].manual = entry.before === null ? null : [...entry.before]; state.future.push(entry); note(state, "Schedule", `Undo restored ${state.slots[entry.slotId].label}.`); playSfx(state, "soft"); dirty(state); }
function redo(state) { const entry = state.future.pop(); if (!entry || !state.slots[entry.slotId]) return; state.slots[entry.slotId].manual = entry.after === null ? null : [...entry.after]; state.history.push(entry); note(state, "Schedule", `Redo re-applied ${state.slots[entry.slotId].label}.`); playSfx(state, "soft"); dirty(state); }
function mentor(state) { let pairs = 0; state.employees.filter((employee) => employee.active && employee.trainee && !employee.mentorId).forEach((trainee) => { const mentor = state.employees.filter((employee) => employee.active && !employee.trainee && employee.experienceYears >= 15 && (employee.primary === trainee.primary || employee.secondary.includes(trainee.primary))).sort((a, b) => Math.abs((a.skills[trainee.primary] || 0) - (trainee.skills[trainee.primary] || 0)) - Math.abs((b.skills[trainee.primary] || 0) - (trainee.skills[trainee.primary] || 0)))[0]; if (mentor) { trainee.mentorId = mentor.id; mentor.menteeIds = uniq([...mentor.menteeIds, trainee.id]); pairs += 1; } }); note(state, "Talent", pairs ? `Auto mentor paired ${pairs} trainee${pairs === 1 ? "" : "s"}.` : "Auto mentor found no unpaired trainee."); playSfx(state, "mentor"); syncDerived(state); }
function training(state) { if (state.stats.cash < 280_000) return note(state, "Finance", "Training program blocked by cash constraints."); state.stats.cash -= 280_000; state.fin.training += 280_000; state.progs.training = Math.max(state.progs.training, 4); note(state, "Talent", "Focused training activated for the next 4 half-shifts."); playSfx(state, "mentor"); }
function handover(state) { if (state.stats.cash < 180_000) return note(state, "Finance", "Knowledge transfer blocked by cash constraints."); state.stats.cash -= 180_000; state.fin.training += 180_000; state.progs.handover = Math.max(state.progs.handover, 4); note(state, "Talent", "Handover sprint started for high-risk roles."); playSfx(state, "mentor"); }
function recruit(state) { const candidate = state.pool.shift(); if (!candidate) return note(state, "Talent", "Talent pool is empty."); const cost = 720_000 + state.mods.recruit * 180_000; if (state.stats.cash < cost) { state.pool.unshift(candidate); return note(state, "Finance", "Emergency hire blocked by cash constraints."); } if (candidate.workType === "shift") candidate.crew = ["A", "B", "C", "D"].sort((a, b) => crewCount(state, a) - crewCount(state, b))[0]; candidate.hired = true; state.stats.cash -= cost; state.fin.recruit += cost; state.employees.push(candidate); state.map.set(candidate.id, candidate); if (!state.selected) state.selected = candidate.id; note(state, "Talent", `Emergency hire onboarded ${candidate.name} (${candidate.role}).`); playSfx(state, "assign"); syncDerived(state); }
function randomEvent(state) { choice([() => { const delta = Math.random() > 0.5 ? 0.12 : -0.12; state.mods.market = clamp(state.mods.market + delta, 0.78, 1.25); note(state, "Market", `Oil price ${delta > 0 ? "spiked" : "softened"}. Revenue is now ${state.mods.market.toFixed(2)}x.`); }, () => { state.mods.reg = clamp(state.mods.reg + 0.1, 0, 0.55); note(state, "HSE", "New regulatory checklist raised compliance pressure."); }, () => { state.mods.labor = clamp(state.mods.labor + 0.12, 0, 0.6); state.stats.harmony = clamp(state.stats.harmony - 4, 0, 100); note(state, "Labor", "Union demand spike increased welfare expectations."); }, () => { state.mods.recruit = clamp(state.mods.recruit + 0.15, 0, 0.7); note(state, "Talent", "Hiring competition accelerated near the site."); }, () => { state.mods.bloomBias = clamp(state.mods.bloomBias + (Math.random() > 0.5 ? 0.18 : -0.16), -0.4, 0.4); note(state, "Weather", "Blossom weather outlook shifted."); }, () => { state.employees.filter((employee) => employee.active && employee.experienceYears >= 18).slice(0, 3).forEach((employee) => { employee.retirementRisk = clamp(employee.retirementRisk + 0.08, 0, 1); }); note(state, "Talent", "Retirement wave warning hit senior operations roles."); }])(); playSfx(state, "alarm"); }
function retire(state) { const employee = state.employees.filter((item) => item.active && item.retirementRisk >= 0.82).sort((a, b) => b.retirementRisk - a.retirementRisk)[0]; if (!employee) return; employee.active = false; note(state, "Talent", `${employee.name} entered retirement leave. Backfill pressure increased.`); playSfx(state, "alarm"); }
function scoreEvent(state, dayIndex, score) { if (score !== null) { state.blossom.scores = state.blossom.scores.filter((item) => item.day !== dayIndex); state.blossom.scores.push({ day: dayIndex, score }); } const end = state.blossom.open + state.blossom.duration; if (!state.blossom.done && dayIndex > end) { const avgScore = avg(state.blossom.scores.map((item) => item.score)); if (avgScore >= 0.72) { state.stats.community = clamp(state.stats.community + 7, 0, 100); state.stats.harmony = clamp(state.stats.harmony + 4, 0, 100); state.stats.cash += 1_250_000; note(state, "Community", "Blossom event closed above plan. Reputation and sponsorship improved."); } else { state.stats.community = clamp(state.stats.community - 6, 0, 100); state.stats.trir = clamp(state.stats.trir + 0.08, 0, 2.5); note(state, "Community", "Blossom event closed with complaints and added safety scrutiny."); } state.blossom.done = true; } }
function syncDerived(state) { state.stats.fatigue = avg(state.employees.filter((employee) => employee.active).map((employee) => employee.fatigue)); state.stats.succession = avg(["control", "cracker", "olefins", "aromatics", "utilities", "tankFarm", "safetyDesk", "hq"].map((key) => clamp(state.employees.filter((employee) => employee.active && (employee.skills[key] || 0) >= 68 && employee.successionReadiness >= 62 && employee.retirementRisk < 0.9).length / 2, 0, 1))) * 100; state.alerts = buildAlerts(state); }
function buildAlerts(state) { const current = resolve(state, state.current), out = []; current.slots.forEach((slot) => slot.crit && slot.cov < 1 && out.push({ t: "critical", text: `${slot.label} is underfilled for the active period.` })); if (state.stats.trir >= 0.95) out.push({ t: "critical", text: `TRIR has climbed to ${state.stats.trir.toFixed(2)}.` }); if (state.stats.harmony <= 63) out.push({ t: "warn", text: `Labor harmony is slipping (${Math.round(state.stats.harmony)}).` }); if (state.stats.succession <= 62) out.push({ t: "warn", text: `Critical succession coverage is only ${Math.round(state.stats.succession)}%.` }); if (state.stats.cash <= 170_000_000) out.push({ t: "warn", text: "Cash has fallen below the comfort band." }); const d = state.blossom.open - Math.floor(state.current / 2); if (d >= 0 && d <= 2) out.push({ t: "critical", text: `Blossom opening begins in ${d} day${d === 1 ? "" : "s"}.` }); return out.slice(0, 4); }
function weatherKey(state, dayIndex) { const key = `d${dayIndex}`; if (!state.weather[key]) { const roll = Math.random(), bias = state.mods.bloomBias; state.weather[key] = roll < 0.44 + bias * 0.08 ? "clear" : roll < 0.68 + bias * 0.04 ? "haze" : roll < 0.88 - bias * 0.06 ? "windy" : "rain"; } return state.weather[key]; }
function zoneHeat(state) { const current = resolve(state, state.current), out = {}; current.slots.forEach((slot) => { out[slot.zone] = slot.q; }); out.union = clamp(state.stats.harmony / 100, 0, 1); out.training = clamp(state.stats.succession / 100 + (state.progs.training ? 0.12 : 0), 0, 1); out.blossom = eventDay(state, Math.floor(state.current / 2)) ? clamp(state.stats.community / 100, 0, 1) : 0.55; return out; }
function eventDay(state, dayIndex) { return dayIndex >= state.blossom.open && dayIndex < state.blossom.open + state.blossom.duration; }
function note(state, tag, text) { state.logs.unshift({ tag, text, time: stamp(new Date(START.getTime() + state.current * PERIOD_MS)) }); state.logs = state.logs.slice(0, 24); }
function dirty(state) { state.dirty = true; }
function clearDrop(state) { state.refs.board.querySelectorAll(".is-drop-target").forEach((node) => node.classList.remove("is-drop-target")); }
function pay(employee) { return employee.workType === "shift" ? 8600 + employee.experienceYears * 160 : 7900 + employee.experienceYears * 140; }
function crewCount(state, crew) { return state.employees.filter((employee) => employee.active && employee.crew === crew).length; }
function weighted(slots) { const weight = slots.reduce((sum, slot) => sum + slot.w, 0); return weight ? slots.reduce((sum, slot) => sum + slot.q * slot.w, 0) / weight : 0; }
function countDuplicates(slots) { const counts = new Map(); slots.forEach((slot) => slot.employeeIds.forEach((id) => counts.set(id, (counts.get(id) || 0) + 1))); return [...counts.values()].filter((value) => value > 1).length; }
function countMismatches(slots, info) { let total = 0; slots.forEach((slot) => slot.people.forEach((employee) => { if (!slot.types.includes(employee.workType) || (employee.workType === "day" && info.shift === "night")) total += 1; })); return total; }
function decay(state) { state.progs.training = Math.max(0, state.progs.training - 1); state.progs.handover = Math.max(0, state.progs.handover - 1); state.mods.reg = lerp(state.mods.reg, 0.16, 0.06); state.mods.labor = lerp(state.mods.labor, 0.12, 0.05); state.mods.recruit = lerp(state.mods.recruit, 0.08, 0.05); state.mods.market = lerp(state.mods.market, 1, 0.05); state.mods.bloomBias = lerp(state.mods.bloomBias, 0, 0.04); }
